#include "Stage/Stage.h"

static const StageCommand command0[] = {
	STAGE_CMD_NUM(StageForward, 500),
	STAGE_CMD_NUM(StageTurn, 90.0),
	STAGE_CMD_NUM(StageForward, 400),
	STAGE_CMD_MAIXCAM(((const uint8_t[]){0x01U, 0x01U}), 2U),
	STAGE_CMD_NUM(StageTurn, -90.0),
	STAGE_CMD_NUM(StageForward, 480),
	STAGE_CMD_NUM(StageTurn, -90.0),
	STAGE_CMD_NUM(StageForward, 1000),
	STAGE_CMD_NUM(StageTurn, -90.0),
	STAGE_CMD_MAIXCAM(((const uint8_t[]){0x01U, 0x02U}), 2U),
	STAGE_CMD_DATA(StageForward, (&(StageForwardData){110.0, 150})),
	STAGE_CMD_MAIXCAM(((const uint8_t[]){0x01U, 0x02U}), 2U),
	STAGE_CMD_DATA(StageForward, (&(StageForwardData){110.0, 150})),
	STAGE_CMD_MAIXCAM(((const uint8_t[]){0x01U, 0x02U}), 2U),
	STAGE_CMD_DATA(StageForward, (&(StageForwardData){110.0, 150})),
	STAGE_CMD_MAIXCAM(((const uint8_t[]){0x01U, 0x02U}), 2U),
	STAGE_CMD_DATA(StageForward, (&(StageForwardData){110.0, 150})),
	STAGE_CMD_MAIXCAM(((const uint8_t[]){0x01U, 0x02U}), 2U),
	STAGE_CMD_DATA(StageForward, (&(StageForwardData){110.0, 150})),
	STAGE_CMD_MAIXCAM(((const uint8_t[]){0x01U, 0x02U}), 2U),
	STAGE_CMD_DATA(StageForward, (&(StageForwardData){110.0, 150})),
	STAGE_CMD_MAIXCAM(((const uint8_t[]){0x01U, 0x02U}), 2U),
	STAGE_CMD_DATA(StageForward, (&(StageForwardData){110.0, 150})),
	STAGE_CMD_MAIXCAM(((const uint8_t[]){0x01U, 0x02U}), 2U),
	STAGE_CMD_DATA(StageForward, (&(StageForwardData){110.0, 150})),
	STAGE_CMD_MAIXCAM(((const uint8_t[]){0x01U, 0x02U}), 2U),
	// STAGE_CMD_NUM(StageTurn, -180),
	// STAGE_CMD_NUM(StageForward, 330),
	// STAGE_CMD_NUM(StageTurn, 90.0),
	// STAGE_CMD_NUM(StageForward, 900),
	STAGE_CMD(StageStop),
};

static const StageCommand command1[] = {
	STAGE_CMD(StageStartJudge), STAGE_CMD(StageRush),
	STAGE_CMD(StageLeftRound),	STAGE_CMD(StageLeft),
	STAGE_CMD(StageRush),		STAGE_CMD(StageLeftRound),
	STAGE_CMD(StageLeft),		STAGE_CMD(StageRush),
	STAGE_CMD(StageLeftRound),	STAGE_CMD(StageLeft),
	STAGE_CMD(StageRush),		STAGE_CMD(StageFake),
	STAGE_CMD(StageRightRound), STAGE_CMD(StageRight),
	STAGE_CMD(StageRush),		STAGE_CMD(StageFake),
	STAGE_CMD(StageRightRound), STAGE_CMD(StageRight),
	STAGE_CMD(StageRush),		STAGE_CMD(StageRightRound),
	STAGE_CMD(StageRight),		STAGE_CMD(StageStop),
	STAGE_CMD(StageStop),		STAGE_CMD(StageRush),
	STAGE_CMD(StageRightRound), STAGE_CMD(StageRight),
	STAGE_CMD(StageRush),		STAGE_CMD(StageRightRound),
	STAGE_CMD(StageRight),		STAGE_CMD(StageRush),
	STAGE_CMD(StageFake),		STAGE_CMD(StageRightRound),
	STAGE_CMD(StageRight),		STAGE_CMD(StageRush),
	STAGE_CMD(StageLeftRound),	STAGE_CMD(StageLeft),
	STAGE_CMD(StageRush),		STAGE_CMD(StageLeftRound),
	STAGE_CMD(StageLeft),		STAGE_CMD(StageRush),
	STAGE_CMD(StageFake),		STAGE_CMD(StageLeftRound),
	STAGE_CMD(StageLeft),		STAGE_CMD(StageStop),
	STAGE_CMD(StageStop),		STAGE_CMD(StageEnd),
};

static const StageCommand command2[] = {
	STAGE_CMD(StageStartJudge), STAGE_CMD(StageRush),
	STAGE_CMD(StageLeftRound),	STAGE_CMD(StageLeft),
	STAGE_CMD(StageRush),		STAGE_CMD(StageLeftRound),
	STAGE_CMD(StageCross),		STAGE_CMD(StageRush),
	STAGE_CMD(StageLeft),		STAGE_CMD(StageRush),
	STAGE_CMD(StageLeftRound),	STAGE_CMD(StageLeft),
	STAGE_CMD(StageRush),		STAGE_CMD(StageLeftRound),
	STAGE_CMD(StageLeft),		STAGE_CMD(StageStop),
	STAGE_CMD(StageStop),		STAGE_CMD(StageStop),
	STAGE_CMD(StageStop),		STAGE_CMD(StageStop),
	STAGE_CMD(StageStop),		STAGE_CMD(StageStop),
	STAGE_CMD(StageStop),		STAGE_CMD(StageRush),
	STAGE_CMD(StageRightRound), STAGE_CMD(StageRight),
	STAGE_CMD(StageRush),		STAGE_CMD(StageRightRound),
	STAGE_CMD(StageRight),		STAGE_CMD(StageRush),
	STAGE_CMD(StageRightRound), STAGE_CMD(StageCross),
	STAGE_CMD(StageRush),		STAGE_CMD(StageRight),
	STAGE_CMD(StageRush),		STAGE_CMD(StageRightRound),
	STAGE_CMD(StageRight),		STAGE_CMD(StageStop),
	STAGE_CMD(StageStop),		STAGE_CMD(StageEnd),
};

static const StageCommand command3[] = {
	STAGE_CMD(StageRush), STAGE_CMD(StageLeftRound),	 STAGE_CMD(StageLeft),
	STAGE_CMD(StageRush), STAGE_CMD(StageLeftRound),	 STAGE_CMD(StageCross),
	STAGE_CMD(StageRush), STAGE_CMD(StageSkip),			 STAGE_CMD(StageLeft),
	STAGE_CMD(StageRush), STAGE_CMD(StageLeftRound),	 STAGE_CMD(StageLeft),
	STAGE_CMD(StageRush), STAGE_CMD(StageLeftRound),	 STAGE_CMD(StageLeft),
	STAGE_CMD(StageRush), STAGE_CMD(StageLeftRound),	 STAGE_CMD(StageLeft),
	STAGE_CMD(StageRush), STAGE_CMD_NUM(StageTurn, 145), STAGE_CMD(StageFinsih),
	STAGE_CMD(StageEnd),
};

const StageCommand *const commandList[STAGE_COMMAND_LIST_COUNT] = {
	command0,
	command1,
	command2,
	command3,
};
